//@dev adding a network here means that every subgraph for that chain
//     will be generated by this service
export const rpcUrl: Record<number, string> = {
  5234: "https://explorer-rpc-http.mainnet.stages.humanode.io",
};
